<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-03-18 23:14
=======
# Generated by Django 5.1.2 on 2025-03-18 23:40
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
=======
# Generated by Django 5.1.2 on 2025-03-18 23:40
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storefront.product')),
=======
=======
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_id", models.BigIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency_code", models.CharField(max_length=10)),
                ("quantity", models.IntegerField()),
                ("url", models.URLField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_id", models.BigIntegerField()),
                ("shop_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeaturedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField()),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storefront.product",
                    ),
                ),
<<<<<<< HEAD
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
=======
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
            ],
        ),
    ]
