# Generated by Django 5.1.2 on 2025-03-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
