<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-03-18 23:14
=======
# Generated by Django 5.1.2 on 2025-03-18 23:40
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('blog', '0001_initial'),
=======
        ("blog", "0001_initial"),
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
=======
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="blog.tag"),
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
        ),
    ]
