<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-03-18 23:14
=======
# Generated by Django 5.1.2 on 2025-03-18 23:40
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('core', '0001_initial'),
=======
        ("core", "0001_initial"),
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_expiration',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='subheader',
=======
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="gallery/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="announcement",
            name="date_expiration",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="link",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="subheader",
>>>>>>> 552a20e72ab5e4e1281f6e5c46961712b3165e55
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
