# Generated by Django 5.1.2 on 2025-03-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_gallery_alter_announcement_date_expiration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="interests",
        ),
        migrations.AddField(
            model_name="subscriber",
            name="wants_newsletter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="wants_product_updates",
            field=models.BooleanField(default=False),
        ),
    ]
